# ================================
#       Jekyll Site Config
# ================================

# --- Basic Site Info ---
locale: "en-US"
site_theme: "default"
title: "Dr. Farrukh Aziz | AI, Leadership & Behavioral Sciences"
title_separator: "—"
name: &name "Dr. Farrukh Aziz"
description: &description "PhD Researcher at Dalian University of Technology | AI-driven decision-making | Leadership impact | Lean manufacturing | Financial risk management"
url: https://engrfarrukhaziz.github.io
baseurl: ""     # e.g., "/blog" if hosted in a subfolder
repository: "engrfarrukhaziz/engrfarrukhaziz.github.io"

# --- Author Profile (Sidebar & Sitewide) ---
author:
  avatar: "profile.png"                    # Place your profile picture here
  name: "Dr. Farrukh Aziz"
  pronouns: "he/him"
  bio: >
    Passionate about blending AI with behavioral science to transform decision-making and leadership.
    Currently pursuing PhD at Dalian University of Technology, China.
  location: "Dalian, China"
  employer: "Dalian University of Technology"
  uri: "https://engrfarrukhaziz.github.io"
  email: "engrfarrukhaziz@mail.dlut.edu.cn"

  # Academic Profiles
  academia: ""
  arxiv: ""
  googlescholar: "https://scholar.google.com/citations?hl=en&user=ulUkkPus9M0C"
  inspire-hep: ""
  impactstory: ""
  orcid: "https://orcid.org/0000-0001-7088-0371"
  semantic: ""
  pubmed: ""
  researchgate: "https://www.researchgate.net/profile/Farrukh-Aziz-6"
  scopus: ""

  # Code & Development
  bitbucket: ""
  codepen: ""
  dribbble: ""
  github: "engrfarrukhaziz"
  kaggle: ""
  stackoverflow: ""

  # Social Media Handles (Fill as needed)
  twitter: ""
  linkedin: ""
  facebook: ""
  instagram: ""
  mastodon: ""
  telegram: ""
  youtube: ""

# --- Publications Categories ---
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# --- Site Appearance & Behavior ---
teaser: ""                      # e.g., "banner.jpg" to show a homepage teaser image
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# --- Comments System ---
comments:
  provider: false               # Options: false, disqus, discourse, facebook, google-plus, staticman, custom
  disqus:
    shortname: ""
  discourse:
    server: ""
  facebook:
    appid: ""
    num_posts: 5
    colorscheme: "light"
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"

# --- RSS & Feeds ---
atom_feed:
  hide: false
  path: ""

# --- SEO Verification Tokens (if any) ---
google_site_verification: ""
bing_site_verification: ""
alexa_site_verification: ""
yandex_site_verification: ""

# --- Social Sharing Defaults ---
twitter:
  username: ""
facebook:
  username: ""
  app_id: ""
  publisher: ""
og_image: ""
og_description: ""

social:
  type: Person
  name: "Dr. Farrukh Aziz"
  links: []

# --- Analytics ---
analytics:
  provider: "false"             # Options: false, google, google-universal, google-analytics-4, custom
  google:
    tracking_id: ""

# --- Site Content Handling ---
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# --- Markdown & Syntax Highlighting ---
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# --- Collections & Permalinks ---
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# --- Defaults for content types ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# --- Styling ---
sass:
  sass_dir: _sass
  style: compressed

# --- URL Structure ---
permalink: /:categories/:title/
timezone: Etc/UTC

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# --- Archives Configuration ---
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# --- HTML Compression for Performance ---
compress_html:
  clippings: all
  ignore:
    envs: development
